export const ROUTES = {
  LANDING: '/', // 스플래시(랜딩) 페이지 - 3초 후 로그인으로 이동
  LOGIN: '/login',
  SIGNUP: '/signup',
  SIGNUP_INFO: '/signup/info',
  SIGNUP_COMPLETE: '/signup/complete',
  HOME: '/home',
  SCHEDULE: '/schedule',
  EMPLOYEE: '/employee',
  PAYROLL: '/payroll',
  STORE: '/store',
  STORE_COMMUNITY: '/store/community',
  STORE_CHAT_NEW: '/store/community/chat/new',
  STORE_CHAT_ROOM: '/store/community/chat/:chatRoomId',
  STORE_BOARD_NEW: '/store/community/board/new',
  STORE_BOARD_DETAIL: '/store/community/board/:postId',
  TODO: '/todo',
  TODO_NEW: '/todo/new',
  TODO_DETAIL: '/todo/:id',
  TODO_EDIT: '/todo/:id/edit',
  AUCTION: '/auction',
  BOARD: '/board',
  ATTENDANCE: '/attendance',
  CHATBOT: '/chatbot',
  REPORT: '/report',
  NOTIFICATION: '/notification',
} as const;
