export const ROUTES = {
  HOME: '/',
  SCHEDULE: '/schedule',
  EMPLOYEE: '/employee',
  PAYROLL: '/payroll',
  STORE: '/store',
  TODO: '/todo',
  TODO_NEW: '/todo/new',
  TODO_DETAIL: '/todo/:id',
  TODO_EDIT: '/todo/:id/edit',
  AUCTION: '/auction',
  BOARD: '/board',
  ATTENDANCE: '/attendance',
  CHATBOT: '/chatbot',
  REPORT: '/report',
  NOTIFICATION: '/notification',
} as const;
