spring:
  config:
    activate:
      on-profile: prod

  datasource:
    url: jdbc:postgresql://${DB_HOST}:${DB_PORT}/${DB_NAME}
    driver-class-name: org.postgresql.Driver
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    hikari:
      maximum-pool-size: 10 # 커넥션 풀 크기 명시적 설정
      connection-timeout: 30000

  jpa:
    hibernate:
      ddl-auto: validate # 프로덕션 환경에서는 절대 update나 create를 사용하지 마세요
    show-sql: false

logging:
  file:
    name: logs/application.log # 프로덕션 환경에서는 파일에 로그 기록
  level:
    root: info
